name: Publish to GCR

on:
  push:
    branches:
      - master

env:
  ARTIFACT_NAME: eks-nvme-ssd-provisioner
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: devops-estudos/eks-nvme-ssd-provisioner

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=,format=long
            type=sha,prefix=,format=short
          labels: |
            com.github.actions.source-url=https://github.com/${{ env.IMAGE_NAME }}
            com.github.actions.source-ref=HEAD
            com.github.actions.source-sha=${{ github.sha }}
            com.github.actions.source-ref-name=${{ github.ref_name }}
            com.github.actions.source-ref-type=${{ github.ref_type }}
            com.github.actions.source-ref-sha=${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true

          context: .
          file: Dockerfile.alpine

          cache-from: type=gha
          cache-to: type=gha,mode=max

          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}